### ISSUE TITLE
Setup project infrastructure

### ISSUE THREAD

**Issue by a-savka** [teleboto/prodavan#11]

**Comment by a-savka** [comment]
Подготовить инфраструктуру для развертывания проекта:
  Подобрать VPS сервер
  Проверить/установить необходимое ПО (python, postgres, web server)

**Comment by Satta-Massagana** [comment]
Ubuntu 22.04, PostgreSQL 14.11, Python 3.10, OpenSSH 8.9, xrdp, xorgxrdp, Xfce

Конфигурация VDS:
2x2.2ГГц CPU, 4 ГБ RAM, 40 ГБ SSD RAID, 1 статический IP
